
baseURL = "https://quizplorer.com/"
languageCode = "en-us"
title = "Quizplorer"
theme = "ananke"

enableRobotsTXT = true
buildFuture = false

[pagination]
pagerSize = 10
[params]
  mainSections = ["posts"]
